name = "dense-ev"
url = "https://github.com/atlytle/dense-ev"
description = "Implements expectation value measurements in Qiskit using optimal dense grouping. Dense-ev provides an improvement of ~2^m over naive grouping and (3/2)^m over qubit-wise commuting groups. Based on arXiv:2305.11847."
licence = "Apache License 2.0"
contact_info = "atlytle@gmail.com"
alternatives = "_No response_"
affiliations = "University of Illinois at Urbana-Champaign"
labels = [ "paper implementation",]
tier = "Community"
website = "https://github.com/atlytle/dense-ev"
styles_results = []
coverages_results = []
skip_tests = false
[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992128"
qiskit_version = "0.44.1"
timestamp = 1692442550.648688

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992128"
qiskit_version = "0.44.1"
timestamp = 1692442550.644942

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992128"
qiskit_version = "0.44.1"
timestamp = 1692442550.644942

