name = "purplecaffeine"
url = "https://github.com/IceKhan13/purplecaffeine"
description = "Project is aimed to create simple general interface to track quantum experiments, store and search them in an easy way."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "QAMP"
website = "https://icekhan13.github.io/purplecaffeine/index.html"
labels = [ "plugin", "notebook",]
created_at = 1688661859.080258
updated_at = 1688661859.080264
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 6
[[tests_results]]
passed = true
<<<<<<< Updated upstream
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992059"
qiskit_version = "0.44.1"
timestamp = 1692442671.418165

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992059"
qiskit_version = "0.44.1"
timestamp = 1692442671.41469

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992059"
qiskit_version = "0.44.1"
timestamp = 1692442671.41469
=======
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992034"
qiskit_version = "0.44.1"
timestamp = 1692442703.288483

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992034"
qiskit_version = "0.44.1"
timestamp = 1692442703.288483
>>>>>>> Stashed changes

