name = "q-kernel-ops"
url = "https://github.com/Travis-S-IBM/q-kernel-ops"
description = "Code base on the paper Kernel Matrix Completion for Offline Quantum-Enhanced Machine Learning [2112.08449](https://arxiv.org/abs/2112.08449)."
licence = "Apache 2.0"
contact_info = "### Email"
alternatives = "### Alternatives"
labels = [ "QAMP",]
created_at = 1678827878.663275
updated_at = 1678827878.663276
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 3
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022887"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"
qiskit_version = "unknown"
timestamp = 1692442490.998936

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046565"
qiskit_version = "unknown"
timestamp = 1692442490.998942

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992179"
qiskit_version = "unknown"
timestamp = 1692442490.995331

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654390"
qiskit_version = "-"
timestamp = 1692442490.998952

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654418"
qiskit_version = "-"
timestamp = 1692442490.998955

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654437"
package_commit_hash = "055fe0f9c9ca3b3b994f68ba2c7647763a29f63b"
qiskit_version = "-"
timestamp = 1692442490.998958

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022887"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"
qiskit_version = "unknown"
timestamp = 1692442490.998961

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046565"
qiskit_version = "unknown"
timestamp = 1692442490.998964

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/mickahell/ecosystem/actions/runs/5910992179"
qiskit_version = "unknown"
timestamp = 1692442490.995331

