name = "qBraid"
url = "https://github.com/qBraid/qBraid"
description = "Blabla blablabalfbjefbef\\ egnrgnrohnro - bgrbgr - ndgrjkrhr **grnhrh** rhrohor `grogrhr.com`"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "paper implementation", "simulation", "chemistry",]
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
