name = "qiskit-nature"
url = "https://github.com/qiskit-community/qiskit-nature"
description = "................"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = []
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
