name = "qiskit-ecosystem_template"
url = "https://github.com/mickahell/qiskit-ecosystem_template"
description = "Ellipsis"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = []
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
